name: "2 - [DEV] Build & Deploy"

on:
  pull_request:
    types: closed
    branches: develop

jobs:
  validate-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir autor e branch
        run: |
          echo "Autor: ${{ github.actor }}"
          echo "Branch: ${{ github.head_ref }}"
