name: "2 - [DEV] Update Pr With Changeset"

on:
  pull_request:
    types:
      - synchronize
      - opened
    branches:
      - develop

jobs:
  validate-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir autor e branch
        run: |
          echo "Autor: ${{ github.actor }}"
          echo "Branch: ${{ github.head_ref }}"
