name: "3 - [HOM] Promote & Deploy"

on:
  pull_request:
    types: closed
    branches: 'release/**'

jobs:
  validate-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir autor e branch
        run: |
          echo "Autor: ${{ github.actor }}"
          echo "Branch: ${{ github.head_ref }}"