name: "4 - [PROD] Promote & Deploy"

on:
  pull_request:
    types: edited
    branches: main

jobs:
  validate-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir autor e branch
        run: |
          echo "Autor: ${{ github.actor }}"
          echo "Branch: ${{ github.head_ref }}"
